### ISSUE TITLE
Common memory between Node.js and C++ applications.

### ISSUE THREAD

**Issue by GreenVlads** [echo-team/CyberPunk#6]
There is a method, which may help to make a common memory between Node.js and C++ apps. These resources describes a way to make these kind of memory in pairs:
http://qaru.site/questions/350643/shared-memory-between-c-and-java-processes. JAVA - C++
http://vsokovikov.narod.ru/New_MSDN_API/Menage_files/create_name_mem.htm. C++ - C++

**Comment by GreenVlads** [comment]
For a start we need to try to connect two C++ applications with FileMapping method, and I have already made examples of these two connecting apps, but there's data tracking issue.
Now it's working as just tracking last one variable, which was copied in mapped file, but for "Receiving app" there's no difference between last data and the same data. (For example, there's no difference between [47] and [47,47,47] sequences

**Comment by gigafiga21** [comment]
Irrelevant, chose IPC.
